# Traefik configuration file
api:
  dashboard: true
  debug: false
  insecure: true  # Disable in production with proper authentication

# Enable Docker provider
docker:
  endpoint: "unix:///var/run/docker.sock"
  exposedByDefault: false
  network: proxy

# Entrypoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Logging configuration
log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

# Access logs
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  bufferingSize: 100
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Referer: keep

# TLS configuration
providersThrottleDuration: 2s

# Enable Let's Encrypt with Cloudflare DNS challenge
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/cert.pem
        keyFile: /etc/certs/privkey.pem
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      curvePreferences:
        - CurveP521
        - CurveP384
      preferServerCipherSuites: true

# Enable metrics (optional)
metrics:
  prometheus:
    entryPoint: websecure
