version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"  # For Node.js debugging
    environment:
      - NODE_ENV=development
      - DEBUG=app:*,server:*
    command: npm run dev
    stdin_open: true
    tty: true
    
  # Uncomment if you're using a database
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: transcriber_dev
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

volumes:
  postgres_data:
