# WebAudioTranscriber Render.com Configuration
# Docs: https://render.com/docs/render-yaml-spec

services:
  # Main web service
  - type: web
    name: webaudio-transcriber
    env: node
    region: oregon  # Choose a region closest to your users
    plan: free  # Options: free, starter, standard, plus, pro
    
    # Build and start commands
    buildCommand: |
      npm install
      npm run build
      cd client && npm install && npm run build
    startCommand: npm start
    
    # Environment variables
    envVars:
      # Required
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render requires using this port
      - key: WHISPER_MODEL
        value: base  # Options: tiny, base, small, medium, large
      - key: DEVICE
        value: cpu  # Use 'cuda' if GPU is available
      
      # Database (if using)
      - key: DATABASE_URL
        sync: false  # Set this in the Render dashboard
      
      # Security
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: 'true'  # Set to 'false' for development without HTTPS
      
      # Optional
      - key: LOG_LEVEL
        value: info
      - key: MAX_FILE_SIZE
        value: '52428800'  # 50MB in bytes
    
    # Health check
    healthCheckPath: /health
    healthCheckTimeout: 10
    
    # Auto-deploy
    autoDeploy: true
    branch: main  # Branch to auto-deploy from
    
    # Build settings
    build:
      caches:
        - node_modules
        - ~/.npm
      
    # Scaling (for paid plans)
    # numInstances: 1
    # instanceSize: standard-1x
    
    # Custom domains (configure in Render dashboard)
    # domains:
    #   - yourdomain.com
    #   - www.yourdomain.com

# Database service (uncomment and configure if needed)
# databases:
#   - name: webaudio-db
#     databaseName: webaudio
#     user: webaudio_user
#     plan: free  # free, starter, standard, plus, pro
#     region: oregon  # Match with web service
#     ipAllowList:
#       - 0.0.0.0/0  # Restrict in production

# Cache service (uncomment if using Redis)
# services:
#   - type: redis
#     name: webaudio-cache
#     plan: free  # free, starter, standard, plus, pro
#     region: oregon  # Match with web service